#Obstacle marking parameters
obstacle_range: 2.5
raytrace_range: 3.0

robot_radius: 0.20

#footprint: [ [-0.25, -0.25], [-0.25, 0.25], [0.25, 0.25], [0.25, -0.25] ]

inflation_radius: 1.55 # 0.55
transform_tolerance: 0.5

#Configuration for the sensors that the costmap will use to update a map
observation_sources: scan

scan: 
  data_type: LaserScan
  topic: scan
  marking: true
  clearing: true

#Set map type
map_type: costmap