<?xml version="1.0"?>
<robot name="mybot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Left Wheel -->
  <link name="left_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="black"><color rgba="0 0 0 1"/></material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="8" length="${wheel_width}" radius="${wheel_radius}">
			<origin xyz="0.0 0 0.0" rpy="0 0 0"/>
		</xacro:inertial_cylinder>
    </link>
  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel"/>
    <origin xyz="0 ${wheel_distance/2} -${wheel_radius}" rpy="-${pi/2} 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <!-- Right Wheel -->
  <link name="right_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="8" length="${wheel_width}" radius="${wheel_radius}">
			<origin xyz="0.0 0 0.0" rpy="0 0 0"/>
		</xacro:inertial_cylinder>
  </link>
  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel"/>
    <origin xyz="0 -${wheel_distance/2} -${wheel_radius}" rpy="${pi/2} 0 0"/>
    <axis xyz="0 0 -1"/>
  </joint>

  <!-- Front Caster Wheel -->
  <link name="front_caster_wheel">
    <visual>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
      <material name="silver"><color rgba="0.75 0.75 0.75 1"/></material>
    </visual>

    <collision>
      <geometry>
        <sphere radius="${wheel_radius}"/>
      </geometry>
    </collision>

    <xacro:inertial_sphere mass="8" radius="${wheel_radius}">
			<origin xyz="0.0 0 0.0" rpy="0 0 0"/>
		</xacro:inertial_sphere>

  </link>
  <joint name="front_caster_joint" type="fixed">
    <parent link="base_link"/>
    <child link="front_caster_wheel"/>
    <origin xyz="${caster_distance} 0 -${caster_radius}" rpy="${pi/2} 0 0"/>
  </joint>

  <!-- Rear Caster Wheel -->
  <link name="rear_caster_wheel">
    <visual>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
      <material name="silver"/>
    </visual>
    <collision>
      <geometry>
        <sphere radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <xacro:inertial_sphere mass="8" radius="${wheel_radius}">
			<origin xyz="0.0 0 0.0" rpy="0 0 0"/>
		</xacro:inertial_sphere>
  </link>
  <joint name="rear_caster_joint" type="fixed">
    <parent link="base_link"/>
    <child link="rear_caster_wheel"/>
    <origin xyz="-${caster_distance} 0 -${caster_radius}" rpy="0 0 0"/>
  </joint>

</robot>
